INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('stone_axe', 'Stone Axe', 200, 1, 1),
('steel_axe', 'Steel Axe', 250, 1, 1),
('titanium_axe', 'Titanium Axe', 300, 1, 1),
('diamond_axe', 'Diamond Axe', 350, 1, 1),
('petrol_chainsaw', 'Petrol Chainsaw', 750, 1, 1),
('cordless_chainsaw', 'Cordless Chainsaw', 650, 1, 1),
('consaw', 'Consaw', 700, 1, 1),
('fuel_can', 'Fuel Can', 500, 0, 1),
('chainsaw_battery', 'Chainsaw Battery', 300, 0, 1),
('wood_scraps', 'Wood Scraps', 10, 0, 1),
('sawdust', 'Sawdust', 5, 0, 1),
('pine_log', 'Pine Log', 25, 0, 1),
('oak_log', 'Oak Log', 35, 0, 1),
('maple_log', 'Maple Log', 40, 0, 1),
('birch_log', 'Birch Log', 35, 0, 1),
('cedar_log', 'Cedar Log', 45, 0, 1),
('mahogany_log', 'Mahogany Log', 50, 0, 1),
('redwood_log', 'Redwood Log', 55, 0, 1),
('ancient_oak_log', 'Ancient Oak Log', 60, 0, 1),
('pine_plank', 'Pine Plank', 20, 0, 1),
('oak_plank', 'Oak Plank', 30, 0, 1),
('maple_plank', 'Maple Plank', 35, 0, 1),
('birch_plank', 'Birch Plank', 30, 0, 1),
('cedar_plank', 'Cedar Plank', 40, 0, 1),
('mahogany_plank', 'Mahogany Plank', 45, 0, 1),
('redwood_plank', 'Redwood Plank', 50, 0, 1),
('ancient_oak_plank', 'Ancient Oak Plank', 55, 0, 1);