	['stone_axe'] = {
		label = 'Stone Axe',
		weight = 200,
		stack = false,
		close = true,
	},
	['steel_axe'] = {
		label = 'Steel Axe',
		weight = 250,
		stack = false,
		close = true,
	},
	['titanium_axe'] = {
		label = 'Titanium Axe',
		weight = 300,
		stack = false,
		close = true,
	},
	['diamond_axe'] = {
		label = 'Diamond Axe',
		weight = 350,
		stack = false,
		close = true,
	},
	['petrol_chainsaw'] = {
		label = 'Petrol Chainsaw',
		weight = 750,
		stack = false,
		close = true,
	},
	['cordless_chainsaw'] = {
		label = 'Cordless Chainsaw',
		weight = 650,
		stack = false,
		close = true,
	},
	['consaw'] = {
		label = 'Consaw',
		weight = 700,
		stack = false,
		close = true,
	},
	['fuel_can'] = {
		label = 'Fuel Can',
		weight = 500,
		stack = true,
		close = true,
	},
	['chainsaw_battery'] = {
		label = 'Chainsaw Battery',
		weight = 300,
		stack = true,
		close = true,
	},
	['wood_scraps'] = {
		label = 'Wood Scraps',
		weight = 10,
		stack = true,
		close = true,
	},
	['sawdust'] = {
		label = 'Sawdust',
		weight = 5,
		stack = true,
		close = true,
	},
	['pine_log'] = {
		label = 'Pine Log',
		weight = 25,
		stack = true,
		close = true,
	},
	['oak_log'] = {
		label = 'Oak Log',
		weight = 35,
		stack = true,
		close = true,
	},
	['maple_log'] = {
		label = 'Maple Log',
		weight = 40,
		stack = true,
		close = true,
	},
	['birch_log'] = {
		label = 'Birch Log',
		weight = 35,
		stack = true,
		close = true,
	},
	['cedar_log'] = {
		label = 'Cedar Log',
		weight = 45,
		stack = true,
		close = true,
	},
	['mahogany_log'] = {
		label = 'Mahogany Log',
		weight = 50,
		stack = true,
		close = true,
	},
	['redwood_log'] = {
		label = 'Redwood Log',
		weight = 55,
		stack = true,
		close = true,
	},
	['ancient_oak_log'] = {
		label = 'Ancient Oak Log',
		weight = 60,
		stack = true,
		close = true,
	},
	['pine_plank'] = {
		label = 'Pine Plank',
		weight = 20,
		stack = true,
		close = true,
	},
	['oak_plank'] = {
		label = 'Oak Plank',
		weight = 30,
		stack = true,
		close = true,
	},
	['maple_plank'] = {
		label = 'Maple Plank',
		weight = 35,
		stack = true,
		close = true,
	},
	['birch_plank'] = {
		label = 'Birch Plank',
		weight = 30,
		stack = true,
		close = true,
	},
	['cedar_plank'] = {
		label = 'Cedar Plank',
		weight = 40,
		stack = true,
		close = true,
	},
	['mahogany_plank'] = {
		label = 'Mahogany Plank',
		weight = 45,
		stack = true,
		close = true,
	},
	['redwood_plank'] = {
		label = 'Redwood Plank',
		weight = 50,
		stack = true,
		close = true,
	},
	['ancient_oak_plank'] = {
		label = 'Ancient Oak Plank',
		weight = 55,
		stack = true,
		close = true,
	},
