stone_axe = { name = "stone_axe", label = "Stone Axe", weight = 200, type = "item", unique = true, shouldClose = true },
steel_axe = { name = "steel_axe", label = "Steel Axe", weight = 250, type = "item", unique = true, shouldClose = true },
titanium_axe = { name = "titanium_axe", label = "Titanium Axe", weight = 300, type = "item", unique = true, shouldClose = true },
diamond_axe = { name = "diamond_axe", label = "Diamond Axe", weight = 350, type = "item", unique = true, shouldClose = true },
petrol_chainsaw = { name = "petrol_chainsaw", label = "Petrol Chainsaw", weight = 750, type = "item", unique = true, shouldClose = true },
cordless_chainsaw = { name = "cordless_chainsaw", label = "Cordless Chainsaw", weight = 650, type = "item", unique = true, shouldClose = true },
consaw = { name = "consaw", label = "Consaw", weight = 700, type = "item", unique = true, shouldClose = true },
fuel_can = { name = "fuel_can", label = "Fuel Can", weight = 500, type = "item", unique = false, shouldClose = true },
chainsaw_battery = { name = "chainsaw_battery", label = "Chainsaw Battery", weight = 300, type = "item", unique = false, shouldClose = true },
wood_scraps = { name = "wood_scraps", label = "Wood Scraps", weight = 10, type = "item", unique = false, shouldClose = true },
sawdust = { name = "sawdust", label = "Sawdust", weight = 5, type = "item", unique = false, shouldClose = true },
pine_log = { name = "pine_log", label = "Pine Log", weight = 25, type = "item", unique = false, shouldClose = true },
oak_log = { name = "oak_log", label = "Oak Log", weight = 35, type = "item", unique = false, shouldClose = true },
maple_log = { name = "maple_log", label = "Maple Log", weight = 40, type = "item", unique = false, shouldClose = true },
birch_log = { name = "birch_log", label = "Birch Log", weight = 35, type = "item", unique = false, shouldClose = true },
cedar_log = { name = "cedar_log", label = "Cedar Log", weight = 45, type = "item", unique = false, shouldClose = true },
mahogany_log = { name = "mahogany_log", label = "Mahogany Log", weight = 50, type = "item", unique = false, shouldClose = true },
redwood_log = { name = "redwood_log", label = "Redwood Log", weight = 55, type = "item", unique = false, shouldClose = true },
ancient_oak_log = { name = "ancient_oak_log", label = "Ancient Oak Log", weight = 60, type = "item", unique = false, shouldClose = true },
pine_plank = { name = "pine_plank", label = "Pine Plank", weight = 20, type = "item", unique = false, shouldClose = true },
oak_plank = { name = "oak_plank", label = "Oak Plank", weight = 30, type = "item", unique = false, shouldClose = true },
maple_plank = { name = "maple_plank", label = "Maple Plank", weight = 35, type = "item", unique = false, shouldClose = true },
birch_plank = { name = "birch_plank", label = "Birch Plank", weight = 30, type = "item", unique = false, shouldClose = true },
cedar_plank = { name = "cedar_plank", label = "Cedar Plank", weight = 40, type = "item", unique = false, shouldClose = true },
mahogany_plank = { name = "mahogany_plank", label = "Mahogany Plank", weight = 45, type = "item", unique = false, shouldClose = true },
redwood_plank = { name = "redwood_plank", label = "Redwood Plank", weight = 50, type = "item", unique = false, shouldClose = true },
ancient_oak_plank = { name = "ancient_oak_plank", label = "Ancient Oak Plank", weight = 55, type = "item", unique = false, shouldClose = true }