INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('shovel', 'Shovel', 1, 0, 1),
('fertilizer', 'Fertilizer', 1, 0, 1),
('watering_can', 'Water Can', 1, 0, 1),
('coca_seed', 'Coca Seed', 1, 0, 1),
('coca_leaf', 'Coca Leaf', 1, 0, 1),
('weed_leaf', 'Weed Leaf', 1, 0, 1),
('weed_seed', 'Weed Seed', 1, 0, 1),
('weed_leaf_blue', 'Blue Weed Leaf', 1, 0, 1),
('weed_seed_blue', 'Blue Weed Seed', 1, 0, 1),
('weed_leaf_purple', 'Purple Weed Leaf', 1, 0, 1),
('weed_seed_purple', 'Purple Weed Seed', 1, 0, 1),
('poppy_seed', 'Opium Poppy Seed', 1, 0, 1),
('poppy_opium', 'Poppy Opium', 1, 0, 1),
('tomato_seed', 'Tomato Seed', 1, 0, 1),
('tomato', 'Tomato', 1, 0, 1),
('cotton_seed', 'Cotton Seed', 1, 0, 1),
('cotton', 'Cotton', 1, 0, 1),
('potato_seed', 'Potato Seed', 1, 0, 1),
('potato', 'Potato', 1, 0, 1);
