INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('stone_pickaxe', 'Stone Pickaxe', 200, 0, 1),
('iron_pickaxe', 'Iron Pickaxe', 250, 0, 1),
('steel_pickaxe', 'Steel Pickaxe', 300, 0, 1),
('titanium_pickaxe', 'Titanium Pickaxe', 350, 0, 1),
('diamond_pickaxe', 'Diamond Pickaxe', 400, 0, 1),
('quantum_pickaxe', 'Quantum Pickaxe', 450, 0, 1),
('mining_drill', 'Mining Drill', 750, 0, 1),
('laser_drill', 'Laser Drill', 750, 0, 1),
('stone', 'Stone', 10, 0, 1),
('coal_ore', 'Coal Ore', 25, 0, 1),
('copper_ore', 'Copper Ore', 35, 0, 1),
('iron_ore', 'Iron Ore', 45, 0, 1),
('silver_ore', 'Silver Ore', 45, 0, 1),
('gold_ore', 'Gold Ore', 55, 0, 1),
('platinum_ore', 'Platinum Ore', 60, 0, 1),
('titanium_ore', 'Titanium Ore', 70, 0, 1),
('mithril_ore', 'Mithril Ore', 70, 0, 1),
('adamantium_ore', 'Adamantium Ore', 70, 0, 1),
('copper_ingot', 'Copper ingot', 30, 0, 1),
('iron_ingot', 'Iron ingot', 40, 0, 1),
('silver_ingot', 'Silver ingot', 40, 0, 1),
('gold_ingot', 'Gold ingot', 50, 0, 1),
('platinum_ingot', 'Platinum ingot', 55, 0, 1),
('titanium_ingot', 'Titanium ingot', 60, 0, 1),
('mithril_ingot', 'Mithril ingot', 70, 0, 1),
('adamantium_ingot', 'Adamantium ingot', 70, 0, 1);