['stone_pickaxe'] = {
    label = 'Stone Pickaxe',
    weight = 200,
    stack = false,
    close = true,
},
['iron_pickaxe'] = {
    label = 'Iron Pickaxe',
    weight = 250,
    stack = false,
    close = true,
},
['steel_pickaxe'] = {
    label = 'Steel Pickaxe',
    weight = 300,
    stack = false,
    close = true,
},
['titanium_pickaxe'] = {
    label = 'Titanium Pickaxe',
    weight = 350,
    stack = false,
    close = true,
},
['diamond_pickaxe'] = {
    label = 'Diamond Pickaxe',
    weight = 400,
    stack = false,
    close = true,
},
['quantum_pickaxe'] = {
    label = 'Quantum Pickaxe',
    weight = 450,
    stack = false,
    close = true,
},
['mining_drill'] = {
    label = 'Mining Drill',
    weight = 750,
    stack = false,
    close = true,
},
['laser_drill'] = {
    label = 'Laser Drill',
    weight = 750,
    stack = false,
    close = true,
},
['stone'] = {
    label = 'Stone',
    weight = 10,
    stack = true,
    close = true,
},
['coal_ore'] = {
    label = 'Coal Ore',
    weight = 25,
    stack = true,
    close = true,
},
['copper_ore'] = {
    label = 'Copper Ore',
    weight = 35,
    stack = true,
    close = true,
},
['iron_ore'] = {
    label = 'Iron Ore',
    weight = 45,
    stack = true,
    close = true,
},
['silver_ore'] = {
    label = 'Silver Ore',
    weight = 45,
    stack = true,
    close = true,
},
['gold_ore'] = {
    label = 'Gold Ore',
    weight = 55,
    stack = true,
    close = true,
},
['platinum_ore'] = {
    label = 'Platinum Ore',
    weight = 60,
    stack = true,
    close = true,
},
['titanium_ore'] = {
    label = 'Titanium Ore',
    weight = 70,
    stack = true,
    close = true,
},
['mithril_ore'] = {
    label = 'Mithril Ore',
    weight = 70,
    stack = true,
    close = true,
},
['adamantium_ore'] = {
    label = 'Adamantium Ore',
    weight = 70,
    stack = true,
    close = true,
},
['copper_ingot'] = {
    label = 'Copper ingot',
    weight = 30,
    stack = true,
    close = true,
},
['iron_ingot'] = {
    label = 'Iron ingot',
    weight = 40,
    stack = true,
    close = true,
},
['silver_ingot'] = {
    label = 'Silver ingot',
    weight = 40,
    stack = true,
    close = true,
},
['gold_ingot'] = {
    label = 'Gold ingot',
    weight = 50,
    stack = true,
    close = true,
},
['platinum_ingot'] = {
    label = 'Platinum ingot',
    weight = 55,
    stack = true,
    close = true,
},
['titanium_ingot'] = {
    label = 'Titanium ingot',
    weight = 60,
    stack = true,
    close = true,
},
['mithril_ingot'] = {
    label = 'Mithril ingot',
    weight = 70,
    stack = true,
    close = true,
},
['adamantium_ingot'] = {
    label = 'Adamantium ingot',
    weight = 70,
    stack = true,
    close = true,
},