    ["codelock"] = {
        label = 'Codelock',
        weight = 1,
        stack = false,
        close = false,
        description = 'A codelock for securing items.',
    },
    ["boxonesmall"] = {
        label = 'Box One Small',
        weight = 5,
        stack = true,
        close = true,
        description = 'A small storage box.',
    },
    ["boxtwosmall"] = {
        label = 'Box Two Small',
        weight = 5,
        stack = true,
        close = true,
        description = 'A small storage box.',
    },
    ["boxonebig"] = {
        label = 'Box One Big',
        weight = 10,
        stack = true,
        close = true,
        description = 'A big storage box.',
    },
    ["boxtwobig"] = {
        label = 'Box Two Big',
        weight = 10,
        stack = true,
        close = true,
        description = 'A big storage box.',
    },
    ["boxtreebig"] = {
        label = 'Box Three Big',
        weight = 10,
        stack = true,
        close = true,
        description = 'A big storage box.',
    },